# Generated by Django 5.0.2 on 2024-03-08 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_game_games_game_created_1f2afd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='games_game_created_1d9304_idx',
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['created_at'], name='games_game_created_1f2afd_idx'),
        ),
    ]
