# Generated by Django 5.0.2 on 2024-03-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_game_games_game_created_1d9304_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sport',
            field=models.CharField(choices=[('football', 'футбол'), ('tennis', 'теннис'), ('bowling', 'боулинг'), ('beach volleyball', 'пляжный волейбол'), ('volleyball', 'волейбол'), ('ice hockey', 'хоккей на льду'), ('volleyball', 'волейбол')], max_length=255),
        ),
    ]
