# Generated by Django 5.0.2 on 2024-03-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sport',
            field=models.CharField(choices=[('football', 'футбол'), ('tennis', 'теннис'), ('bowling', 'боулинг'), ('beach volleyball', 'пляжный волейбол'), ('volleyball', 'волейбол'), ('ice hockey', 'хоккей на льду'), ('chess', 'шахматы')], max_length=255),
        ),
    ]
