# Generated by Django 5.0.2 on 2024-03-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='images/default-profile-user.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
