# Generated by Django 5.0.2 on 2024-03-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default-profile-user.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
