BEGIN;
DELETE FROM "social_auth_partial";
DELETE FROM "auth_group_permissions";
DELETE FROM "django_session";
DELETE FROM "account_profile";
DELETE FROM "actions_action";
DELETE FROM "games_game_joined_players";
DELETE FROM "auth_permission";
DELETE FROM "social_auth_code";
DELETE FROM "easy_thumbnails_source";
DELETE FROM "social_auth_nonce";
DELETE FROM "account_contact";
DELETE FROM "easy_thumbnails_thumbnaildimensions";
DELETE FROM "social_auth_usersocialauth";
DELETE FROM "auth_user_user_permissions";
DELETE FROM "auth_user";
DELETE FROM "django_admin_log";
DELETE FROM "social_auth_association";
DELETE FROM "django_content_type";
DELETE FROM "easy_thumbnails_thumbnail";
DELETE FROM "games_game";
DELETE FROM "auth_user_groups";
DELETE FROM "auth_group";
UPDATE "sqlite_sequence" SET "seq" = 0 WHERE "name" IN ('social_auth_partial', 'auth_group_permissions', 'django_session', 'account_profile', 'actions_action', 'games_game_joined_players', 'auth_permission', 'social_auth_code', 'easy_thumbnails_source', 'social_auth_nonce', 'account_contact', 'easy_thumbnails_thumbnaildimensions', 'social_auth_usersocialauth', 'auth_user_user_permissions', 'auth_user', 'django_admin_log', 'social_auth_association', 'django_content_type', 'easy_thumbnails_thumbnail', 'games_game', 'auth_user_groups', 'auth_group');
COMMIT;
